In [1]:
import pandas as pd
import numpy as np

In [2]:
cars = pd.read_csv("/kaggle/input/car-price-predictionused-cars/car data.csv")

In [3]:
cars.head()

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [4]:
cars = cars[['Year', 'Selling_Price', 'Present_Price', 'Driven_kms', 'Fuel_Type', 'Selling_type','Transmission']]

In [5]:
cars

,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual
...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual
300,2016,5.30,5.90,5464,Petrol,Dealer,Manual

In [6]:
cars['Year'].value_counts()

Year
2015    61
2016    50
2014    38
2017    35
2013    33
2012    23
2011    19
2010    15
2008     7
2009     6
2006     4
2005     4
2003     2
2007     2
2018     1
2004     1
Name: count, dtype: int64

In [7]:
cars['Selling_Price'].unique()

array([ 3.35,  4.75,  7.25,  2.85,  4.6 ,  9.25,  6.75,  6.5 ,  8.75,
        7.45,  6.85,  7.5 ,  6.1 ,  2.25,  7.75,  3.25,  2.65,  4.9 ,
        4.4 ,  2.5 ,  2.9 ,  3.  ,  4.15,  6.  ,  1.95,  3.1 ,  2.35,
        4.95,  5.5 ,  2.95,  4.65,  0.35,  5.85,  2.55,  1.25,  1.05,
        5.8 , 14.9 , 23.  , 18.  , 16.  ,  2.75,  3.6 ,  4.5 ,  4.1 ,
       19.99,  6.95, 18.75, 23.5 , 33.  , 19.75,  4.35, 14.25,  3.95,
        1.5 ,  5.25, 14.5 , 14.73, 12.5 ,  3.49, 35.  ,  5.9 ,  3.45,
        3.8 , 11.25,  3.51,  4.  , 20.75, 17.  ,  7.05,  9.65,  1.75,
        1.7 ,  1.65,  1.45,  1.35,  1.2 ,  1.15,  1.11,  1.1 ,  1.  ,
        0.95,  0.9 ,  0.75,  0.8 ,  0.78,  0.72,  0.65,  0.6 ,  0.55,
        0.52,  0.51,  0.5 ,  0.48,  0.45,  0.42,  0.4 ,  0.38,  0.31,
        0.3 ,  0.27,  0.25,  0.2 ,  0.18,  0.17,  0.16,  0.15,  0.12,
        0.1 ,  5.75,  5.15,  7.9 ,  4.85, 11.75,  3.15,  6.45,  3.5 ,
        8.25,  5.11,  2.7 ,  6.15, 11.45,  3.9 ,  9.1 ,  4.8 ,  2.  ,
        5.35,  6.25,  5.95,  5.2 ,  3.75, 12.9 ,  5.  ,  5.4 ,  7.2 ,
       10.25,  8.5 ,  8.4 ,  9.15,  6.6 ,  3.65,  8.35,  6.7 ,  5.3 ,
       10.9 ,  8.65,  9.7 ,  2.1 ,  8.99,  7.4 ,  5.65, 10.11,  6.4 ,
        8.55,  9.5 , 11.5 ])

In [8]:
cars['Present_Price'].unique()

array([ 5.59 ,  9.54 ,  9.85 ,  4.15 ,  6.87 ,  9.83 ,  8.12 ,  8.61 ,
        8.89 ,  8.92 ,  3.6  , 10.38 ,  9.94 ,  7.71 ,  7.21 , 10.79 ,
        5.09 ,  7.98 ,  3.95 ,  5.71 ,  8.01 ,  3.46 ,  4.41 ,  4.99 ,
        5.87 ,  6.49 ,  5.98 ,  4.89 ,  7.49 ,  9.95 ,  8.06 ,  7.74 ,
        7.2  ,  2.28 ,  3.76 ,  7.87 ,  3.98 ,  7.15 ,  2.69 , 12.04 ,
        9.29 , 30.61 , 19.77 , 10.21 , 15.04 ,  7.27 , 18.54 ,  6.8  ,
       35.96 , 18.61 ,  7.7  , 36.23 ,  6.95 , 23.15 , 20.45 , 13.74 ,
       20.91 ,  6.76 , 12.48 ,  8.93 , 14.68 , 12.35 , 22.83 , 14.89 ,
        7.85 , 25.39 , 13.46 , 23.73 , 92.6  ,  6.05 , 16.09 , 13.7  ,
       22.78 , 18.64 ,  1.9  ,  1.82 ,  1.78 ,  1.6  ,  1.47 ,  2.37 ,
        3.45 ,  1.5  ,  2.4  ,  1.4  ,  1.26 ,  1.17 ,  1.75 ,  0.95 ,
        0.8  ,  0.87 ,  0.84 ,  0.82 ,  0.81 ,  0.74 ,  1.2  ,  0.787,
        0.99 ,  0.94 ,  0.826,  0.55 ,  0.88 ,  0.51 ,  0.52 ,  0.54 ,
        0.73 ,  0.83 ,  0.64 ,  0.72 ,  1.05 ,  0.57 ,  0.48 ,  0.58 ,
        0.47 ,  0.75 ,  0.65 ,  0.32 ,  6.79 ,  5.7  ,  4.6  ,  4.43 ,
        7.13 ,  8.1  , 14.79 , 13.6  ,  9.4  ,  8.4  ,  5.43 ,  7.6  ,
        9.9  ,  6.82 ,  5.35 ,  7.   ,  5.97 ,  5.8  ,  8.7  , 10.   ,
        7.5  ,  5.9  , 14.   , 11.8  ,  8.5  ,  7.9  ,  6.4  ,  6.1  ,
       13.09 , 11.6  , 11.   , 12.5  ])

In [9]:
cars['Selling_type'].value_counts()

Selling_type
Dealer        195
Individual    106
Name: count, dtype: int64

In [10]:
numerical_features_data = cars[['Year', 'Selling_Price', 'Present_Price', 'Driven_kms']]

In [11]:
print(numerical_features_data.corr())

                   Year  Selling_Price  Present_Price  Driven_kms
Year           1.000000       0.236141      -0.047192   -0.524342
Selling_Price  0.236141       1.000000       0.878914    0.029187
Present_Price -0.047192       0.878914       1.000000    0.203618
Driven_kms    -0.524342       0.029187       0.203618    1.000000

In [12]:
cars.isnull().count()

Year             301
Selling_Price    301
Present_Price    301
Driven_kms       301
Fuel_Type        301
Selling_type     301
Transmission     301
dtype: int64

In [13]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           301 non-null    int64
 1   Selling_Price  301 non-null    float64
 2   Present_Price  301 non-null    float64
 3   Driven_kms     301 non-null    int64
 4   Fuel_Type      301 non-null    object
 5   Selling_type   301 non-null    object
 6   Transmission   301 non-null    object
dtypes: float64(2), int64(2), object(3)
memory usage: 16.6+ KB

In [14]:
cars

,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual
...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual
300,2016,5.30,5.90,5464,Petrol,Dealer,Manual

In [15]:
cars.replace({'Fuel_Type':{'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)
cars.replace({'Selling_type':{'Dealer':0,'Individual':1}},inplace=True)
cars.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

/tmp/ipykernel_1067/626890882.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars.replace({'Fuel_Type':{'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)
/tmp/ipykernel_1067/626890882.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars.replace({'Selling_type':{'Dealer':0,'Individual':1}},inplace=True)
/tmp/ipykernel_1067/626890882.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

In [16]:
cars['Fuel_Type'].value_counts()

Fuel_Type
0    239
1     60
2      2
Name: count, dtype: int64

In [17]:
X = cars.drop('Selling_Price', axis=1)
y = cars['Selling_Price']

In [18]:
X.shape, y.shape

((301, 6), (301,))

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=69)

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [22]:
lin_reg = LinearRegression()

In [23]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [24]:
y_train_pred = lin_reg.predict(X_train)
y_test_pred = lin_reg.predict(X_test)

In [25]:
print("Coefficient of Determination R2 on train set:", lin_reg.score(X_train, y_train))
print("Coefficient of Determination R2 on test set:", lin_reg.score(X_test, y_test))

Coefficient of Determination R2 on train set: 0.8735903127907101
Coefficient of Determination R2 on test set: 0.88512990895136

In [26]:
mse_train = mean_squared_error(y_train_pred, y_train)
mse_test = mean_squared_error(y_test_pred, y_test)

print("Mean Squared Error on train set:", mse_train)
print("Mean Squared Error on test set:", mse_test)

Mean Squared Error on train set: 3.618003857192009
Mean Squared Error on test set: 1.9805671895386392

In [27]:
mae_train = mean_absolute_error(y_train_pred, y_train)
mae_test = mean_absolute_error(y_test_pred, y_test)

print("Mean Absolute Error on train set:", mae_train)
print("Mean Absolute Error on test set:", mae_test)

Mean Absolute Error on train set: 1.2799889619677864
Mean Absolute Error on test set: 1.021641683293004

In [31]:
cars

,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission
0,2014,3.35,5.59,27000,0,0,0
1,2013,4.75,9.54,43000,1,0,0
2,2017,7.25,9.85,6900,0,0,0
3,2011,2.85,4.15,5200,0,0,0
4,2014,4.60,6.87,42450,1,0,0
...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,1,0,0
297,2015,4.00,5.90,60000,0,0,0
298,2009,3.35,11.00,87934,0,0,0
299,2017,11.50,12.50,9000,1,0,0
300,2016,5.30,5.90,5464,0,0,0

In [39]:
new_car = [[2016, 5.90, 5464, 1, 0, 0]] 
predicted_price = lin_reg.predict(new_car)
print('Predicted Selling Price:', predicted_price[0], "Lakhs")

Predicted Selling Price: 6.852161431008199 Lakhs

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [40]:
def train_eval_models(X_train, X_test, y_train, y_test, estimator):
    estimator.fit(X_train, y_train)
    
    y_train_pred = estimator.predict(X_train)
    y_test_pred = estimator.predict(X_test)
    
    print("Coefficient of Determination R2 on train set:", estimator.score(X_train, y_train))
    print("Coefficient of Determination R2 on test set:", estimator.score(X_test, y_test))
    
    print()
    print()
    
    mse_train = mean_squared_error(y_train_pred, y_train)
    mse_test = mean_squared_error(y_test_pred, y_test)

    print("Mean Squared Error on train set:", mse_train)
    print("Mean Squared Error on test set:", mse_test)
    
    print()
    print()
    mae_train = mean_absolute_error(y_train_pred, y_train)
    mae_test = mean_absolute_error(y_test_pred, y_test)

    print("Mean Absolute Error on train set:", mae_train)
    print("Mean Absolute Error on test set:", mae_test)

In [41]:
from sklearn.linear_model import SGDRegressor, Ridge, Lasso

In [42]:
model1 = SGDRegressor()
model2 = Ridge()
model3 = Lasso()

In [43]:
print("Performance of Stochastic Gradient Descent Regressor: ")
train_eval_models(X_train, X_test, y_train, y_test, model1)

Performance of Stochastic Gradient Descent Regressor:
Coefficient of Determination R2 on train set: -2.0478217325943917e+34
Coefficient of Determination R2 on test set: -1.697840223209455e+34


Mean Squared Error on train set: 5.861122743782597e+35
Mean Squared Error on test set: 2.927382235419078e+35


Mean Absolute Error on train set: 5.117538091964811e+17
Mean Absolute Error on test set: 4.443446776701913e+17

In [44]:
print("Performance of Ridge Regressor: ")
train_eval_models(X_train, X_test, y_train, y_test, model2)

Performance of Ridge Regressor:
Coefficient of Determination R2 on train set: 0.8735462746910716
Coefficient of Determination R2 on test set: 0.8876573994521021


Mean Squared Error on train set: 3.619264282859321
Mean Squared Error on test set: 1.936988702641466


Mean Absolute Error on train set: 1.2765250911396824
Mean Absolute Error on test set: 1.0126062665434328

In [45]:
print("Performance of Lasso Regressor: ")
train_eval_models(X_train, X_test, y_train, y_test, model3)

Performance of Lasso Regressor:
Coefficient of Determination R2 on train set: 0.8352275505452198
Coefficient of Determination R2 on test set: 0.8796073302252185


Mean Squared Error on train set: 4.71599424733454
Mean Squared Error on test set: 2.0757863900005638


Mean Absolute Error on train set: 1.3501001998701583
Mean Absolute Error on test set: 1.0552039464063026

In [46]:
new_car = [[2016, 5.90, 5464, 1, 0, 0]] 
predicted_price = model1.predict(new_car)
print('Predicted Selling Price by SGD:', predicted_price[0], "Lakhs")

Predicted Selling Price by SGD: 7.5479570489421e+16 Lakhs

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SGDRegressor was fitted with feature names
  warnings.warn(

In [47]:
new_car = [[2016, 5.90, 5464, 1, 0, 0]] 
predicted_price = model2.predict(new_car)
print('Predicted Selling Price by Ridge:', predicted_price[0], "Lakhs")

Predicted Selling Price by Ridge: 6.791974669188448 Lakhs

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

In [48]:
new_car = [[2016, 5.90, 5464, 1, 0, 0]] 
predicted_price = model2.predict(new_car)
print('Predicted Selling Price by Lasso:', predicted_price[0], "Lakhs")

Predicted Selling Price by Lasso: 6.791974669188448 Lakhs

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(